version: 2

jobs:
  build:
    docker:
      # the Docker image with Cypress dependencies
      - image: cypress/browsers:chrome69
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/app
    parallelism: 1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-npm-deps-{{ checksum "package.json" }}
      - save_cache:
          key: v2-npm-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
            - development/node_modules
            - ~/.cache
      - run:
          name: Building the app for testing
          command: npm run ci:build
      - run:
          name: Running cypress
          command: npm run test
